stockstracker/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('user/', include('users.urls')),
    path('main/', include('mainpage.urls')),
    path('admin/', admin.site.urls),
]

users/urls.py
from audioop import reverse
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from users import views as user_view
from .forms import UserPasswordResetForm, UserSetPasswordForm

app_name = 'users'
urlpatterns = [
    path('register/', user_view.RegistrationView.as_view(), name='register'),
    path('login/', user_view.login_view, name='login'),
    path('logout/', user_view.logout_view, name='logout'),
    path(
        'reset-password/', 
        auth_views.PasswordResetView.as_view(
            form_class=UserPasswordResetForm,
            template_name="users/reset_password.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:reset_password_sent")), 
        name='reset_password'
        ),
    path(
        'reset-password-sent/', 
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/reset_password_sent.html",
            ), 
        name='reset_password_sent'),
    path(
        'reset/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(
            form_class=UserSetPasswordForm,
            template_name="users/password_reset_form.html",
            success_url=reverse_lazy("users:password_reset_complete")
            ), 
        name='password_reset_confirm'),
    path(
        'reset-password-complete/', 
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"), 
        name='password_reset_complete'),
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm, SetPasswordForm
from django.contrib.auth import password_validation, authenticate

class RegisterForm(UserCreationForm):

    email = forms.EmailField(
        max_length=200,
        required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'name': 'email',
            'id': 'floatingInput',
            'placeholder': 'Email address',
        }),
    )

    username = forms.CharField(
        max_length=200,
        required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'name': 'username',
            'id': 'floatingUsername',
            'placeholder': 'Username'
        }),
    )

    first_name = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'name': 'first_name',
            'id': 'floatingFirstName',
            'placeholder': 'First name'
        }),
    )

    last_name = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'name': 'last_name',
            'id': 'floatingLastName',
            'placeholder': 'Surname'
        }),
    )

    password1 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'name': 'password1',
            'id': 'floatingPassword',
            'placeholder':'Password',
        }),
    )

    password2 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'name': 'password2',
            'id': 'floatingConfirmPassword',
            'placeholder':'Confirm password',
        }),
    )

    class Meta:
        model = User
        fields = [
            'email',
            'username', 
            'first_name', 
            'last_name',
            'password1',
            'password2',
            ]

    def clean_email(self):
        """Email validation"""
        email = self.cleaned_data.get('email')
        email_check = User.objects.filter(email__exact=email)
        if email_check.exists():
            raise forms.ValidationError("Email address already exists")
        return email

    def clean_username(self):
        """Username validation"""
        username = self.cleaned_data.get('username')
        username_check = User.objects.filter(username__exact=username)
        if username_check.exists():
            raise forms.ValidationError("Username already exists")
        return username

    # Password validation errors
    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 != password2:
            raise forms.ValidationError("Passwords do not match")
        password_validation.validate_password(password2)
        return password2

class LoginForm(forms.Form):

    username = forms.CharField(
        max_length=200,
        required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'name': 'username',
            'id': 'floatingUsername',
            'placeholder': 'Username'
        }),
    )

    password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'name': 'password',
            'id': 'floatingPassword',
            'placeholder':'Password',
        }),
    )

    class Meta:
        model = User
        fields = [
            'username', 
            'password',
            ]

    def get_current_user(self, username):
        return User.objects.filter(username__exact=username)

    def clean_username(self):
        """Username validation"""
        username = self.cleaned_data.get('username')
        if not self.get_current_user(username).exists():
            raise forms.ValidationError("User does not exist")
        return username

    def clean_password(self):
        """Check whether password is the same as the one in the DB"""
        password = self.cleaned_data.get('password')
        username = self.cleaned_data.get('username')
        if self.get_current_user(username).exists():
            if authenticate(username=username, password=password) is None:
                raise forms.ValidationError("Incorrect password, please try again")
        return password

class UserPasswordResetForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super(UserPasswordResetForm, self).__init__(*args, **kwargs)

    email = forms.EmailField(
        max_length=200,
        required=True,
        widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'name': 'email',
            'id': 'floatingEmail',
            'placeholder': 'Email Address',
            'type': 'email',
        }),
    )

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not User.objects.filter(email__exact=email).exists():
            raise forms.ValidationError("This email is not registered")
        return email

class UserSetPasswordForm(SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super(UserSetPasswordForm, self).__init__(*args, **kwargs)

    new_password1 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'name': 'password1',
            'id': 'floatingPassword1',
            'placeholder':'New Password',
        }),
    )

    new_password2 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'name': 'password2',
            'id': 'floatingPassword2',
            'placeholder':'Confirm Password',
        }),
    )

    def clean_new_password2(self):
        new_password1 = self.cleaned_data.get('new_password1')
        new_password2 = self.cleaned_data.get('new_password2')
        if new_password1 != new_password2:
            raise forms.ValidationError("Passwords do not match, please try again")
        password_validation.validate_password(new_password2)
        return new_password2

users/views.py
from pickle import NONE
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.views.generic import FormView
from django.urls import reverse
from urllib.parse import urlencode
from .forms import RegisterForm, LoginForm
from string import capwords

class RegistrationView(FormView):

    form_class = RegisterForm
    template_name = 'users/register.html'

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form': form})
    
    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            # Capitalize full name before saving
            new_user.first_name = request.POST['first_name'].capitalize()
            new_user.last_name = capwords(request.POST['last_name'])
            new_user.save()
            return redirect('users:login')
        return render(request, self.template_name, {'form': form})


def login_view(request):
    form = LoginForm(request.POST or None)
    if request.method == "POST":
        next = request.POST.get('next') or None
        if form.is_valid():
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                if not next or next == 'None':
                    return redirect(reverse('mainpage:home', kwargs={'pk': request.user.id}))
                return redirect(request.POST.get('next'))
        login_url = reverse('users:login') # get the login url
        query_string =  urlencode({'next': next})
        url = '{}?{}'.format(login_url, query_string) # create the url
        return redirect(url)
    return render(request, 'users/login.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('users:login')

users/templates/users/login.html
{% extends 'base_users.html' %}
{% block title %}Login | StocksTracker{% endblock %}

{% block extra_head_content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'users/style.css' %}">
<script defer>
    // Example starter JavaScript for disabling form submissions if there are invalid fields
    (function () {
    'use strict'

    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    var forms = document.querySelectorAll('.needs-validation')

    // Loop over them and prevent submission
    Array.prototype.slice.call(forms)
        .forEach(function (form) {
        form.addEventListener('submit', function (event) {
            if (!form.checkValidity()) {
            event.preventDefault()
            event.stopPropagation()
            }

            form.classList.add('was-validated')
        }, false)
        })
    })()
</script>
{% endblock %}
{% block content %}
<h2 class="logintext">Log in to StocksTracker</h2>
<hr>
<form action="{% url 'users:login' %}" class="needs-validation" novalidate method="POST">
    {% csrf_token %}
    <div class="row g-2 col-md-12 mb-3 position-relative">
        <div class="form-floating">
            {{ form.username }}
            <label for="floatingUsername" class="form-label">Username</label>
            <div class="invalid-tooltip">
                Enter your username to login
            </div>
        </div>   
    </div>
    <div class="row g-2 col-md-12 mb-3 position-relative">
        <div class="form-floating">
            {{ form.password }}
            <label for="floatingPassword" class="form-label">Password</label>
            <div class="invalid-tooltip">
                Please enter your password
            </div>
        </div>
        {{ form.non_field_errors }}
        {% if form.errors %}
        <div class="errors">
            <div class="alert alert-danger d-flex align-items-center" role="alert">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
                <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                </svg>
                <div>
                {% if form.username.errors %}
                    {% for error in form.username.errors %}
                        <strong>{{ error|escape }}</strong>
                    {% endfor %}
                {% endif %}
                {% if form.password.errors %}
                    {% for error in form.password.errors %}
                        <strong>{{ error|escape }}</strong>
                    {% endfor %}
                {% endif %}
                </div>
            </div>
        </div>
        {% endif %}
    </div>
    <div>
        {% if request.GET.next %}
            {% if not user.is_authenticated %}
            <p class="noaccess">You do not have access to this page, login to proceed</p>
            {% else %}
            <p class="noaccess">Incorrect username/password combination, please try again</p>
            {% endif %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <button id="loginBtn" class="btn btn-success btn.lg" type="submit">Log In</button>
    </div>
</form>
<div class="forget">
    <a class="forget" href="{% url 'users:reset_password' %}">Forgotten password?</a>
</div>
<hr>
<div class="createaccount">
    <a href="{% url 'users:register' %}">
        <button class="btn btn-primary btn.lg">Create New Account</button>
    </a>
</div>      
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'base_users.html' %}
{% block title %}Reset Password Complete | StocksTracker{% endblock %}
{% block extra_head_content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'users/password_reset_complete.css' %}">
{% endblock %}
{% block content %}
<div class="resetComplete">
    <h2 class="reset">Password reset complete</h2>
</div>
<hr>
<div class="notification">
    <P>Your password has been set, you may go ahead and log in now</p>
    <a href="{% url 'users:login' %}">Login</a>
</div>
{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}
{% translate "Click on the following link to set a new password" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate "If clicking the link above doesn't work, please copy and paste the URL in a new browser" %}
{% translate "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% translate "Thanks for using my site!" %}

{% translate "Regards," %}
{% translate "Nicholas Y." %}

{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'base_users.html' %}
{% block title %}Set New Password | StocksTracker{% endblock %}
{% block extra_head_content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'users/password_reset_form.css' %}">
{% endblock %}
{% block content %}
<div class="resetConfirm">
    <h2 class="confirm">Set a new password</h2>
</div>
<hr>
<form method="POST">
    {% csrf_token %}
    <div class="form">
        <div class="info">
            <ul>
                <li>Password must contain at least 8 characters</li>
                <li>Password can't be a commonly used password</li>
                <li>Password can't be entirely numeric</li>
            </ul>
        </div>
        {{ form.non_field_errors }}
        {% if form.errors %}
        <div class="errors">
            <div class="alert alert-danger d-flex align-items-center" role="alert">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
                <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                </svg>
                <div>
                {% if form.new_password2.errors|length < 2 %}
                    {% for error in form.new_password2.errors %}
                    <strong>{{ error|escape }}</strong>
                    {% endfor %}
                {% else %}
                <ul>
                    {% for error in form.new_password2.errors %}
                    <li><strong>{{ error|escape }}</strong></li>
                    {% endfor %}
                </ul>
                {% endif %}
                </div>
            </div>
        </div>
        {% endif %}
        <div class="form-inputs">
            <div class="form-floating">
                {{ form.new_password1 }}
                <label for="floatingPassword1" class="form-label">New Password</label>
                <div class="invalid-tooltip">
                    Please enter a new password
                </div>
            </div>
            <div class="form-floating">
                {{ form.new_password2 }}
                <label for="floatingPassword2" class="form-label">Confirm Password</label>
                <div class="invalid-tooltip">
                    Please confirm your new password
                </div>
            </div>
        </div>
        <div class="button">
            <button id="submitBtn" class="btn btn-success btn.lg" type="submit">Submit</button>
        </div>
    </div>
</form>
{% endblock %}

users/templates/users/register.html
{% extends "base_users.html" %}

{% block title %}Registration | StocksTracker{% endblock %}

{% block extra_head_content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'users/style.css' %}">
<script defer>
    // Example starter JavaScript for disabling form submissions if there are invalid fields
    (function () {
    'use strict'

    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    var forms = document.querySelectorAll('.needs-validation')

    // Loop over them and prevent submission
    Array.prototype.slice.call(forms)
        .forEach(function (form) {
        form.addEventListener('submit', function (event) {
            if (!form.checkValidity()) {
            event.preventDefault()
            event.stopPropagation()
            }

            form.classList.add('was-validated')
        }, false)
        })
    })()
</script>
{% endblock %}
{% block content %}
<div class="signuptext">
    <h2 style="color:var(--color3);">Sign Up</h2>
    <p style="color:var(--color5);">It's quick and easy.</p>
</div>
<hr>
<form action="" class="needs-validation" novalidate method="POST">
    {% csrf_token %}
        <div class="row g-2 col-md-12 mb-3 position-relative">
            <div class="form-floating">
                {{ form.email }}
                <label for="floatingInput" class="form-label">Email address</label>
                <div class="invalid-tooltip">
                    Please provide your email address
                </div>
            </div>   
        </div>
        <div class="row g-2 col-md-12 mb-3 position-relative">
            <div class="form-floating">
                {{ form.username }}
                <label for="floatingUsername" class="form-label">Username</label>
                <div class="invalid-tooltip">
                    You'll use this to login
                </div>
            </div>   
        </div>                
        <div class="row g-2 col-md-12 mb-3 position-relative">
            <div class="form-floating col-md-6">
                {{ form.first_name }}
                <label for="floatingFirstName" class="form-label">First name</label>
                <div class="invalid-tooltip">
                    Please enter your first name
                </div>
            </div>
            <div class="form-floating col-md-6">
                {{ form.last_name }}
                <label for="floatingLastName" class="form-label">Surname</label>
                <div class="invalid-tooltip">
                    Please enter your last name
                </div>
            </div>
        </div>
        <div class="row g-2 col-md-12 mb-3 position-relative">
            <div class="form-floating col-md-6">
                {{ form.password1 }}
                <label for="floatingPassword" class="form-label">Password</label>
                <div class="invalid-tooltip">
                    Enter a password
                </div>
            </div>
            <div class="form-floating col-md-6">
                {{ form.password2 }}
                <label for="floatingConfirmPassword" class="form-label">Confirm Password</label>
                <div class="invalid-tooltip">
                    Enter the password again
                </div>
            </div>
            <div class="errors">
                {{ form.non_field_errors }}
                {% if form.errors %}
                    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
                        <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
                        <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                        </symbol>
                    </svg>
                    <div class="alert alert-danger d-flex align-items-center" role="alert">
                        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
                        <div>
                            <ul>
                                {% if form.email.errors %}
                                    {% for error in form.email.errors %}
                                        <li><strong>{{ error|escape }}</strong></li>
                                    {% endfor %}
                                {% endif %}
                                {% if form.username.errors %}
                                    {% for error in form.username.errors %}
                                        <li><strong>{{ error|escape }}</strong></li>
                                    {% endfor %}
                                {% endif %}
                                {% if form.password2.errors %}
                                    {% for error in form.password2.errors %}
                                        <li><strong>{{ error|escape }}</strong></li>
                                    {% endfor %}
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="col-12">
            <button id="signupBtn" class="btn btn-success btn.lg" type="submit">Sign Up</button>
        </div>
        <div id="login">
            <p style="color:#696969;">
                Have an account?
                <a href="{% url 'users:login' %}">Log in</a>
            </p>
        </div>
    </div>
</form>
{% endblock %}

users/templates/users/reset_password.html
{% extends 'base_users.html' %}
{% block title %}Reset Password | StocksTracker{% endblock %}
{% block extra_head_content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'users/reset_password.css' %}">
{% endblock %}
{% block content %}
<div class="resetText">
    <h2 class="reset">Password reset</h2>
    <p>Enter your email address below, and we'll email instructions for setting a new password</p>
</div>
<hr>
<form method="POST">
    {% csrf_token %}
    <div class="form">
        {{ form.non_field_errors }}
        {% if form.errors %}
        <div class="errors">
            <div class="alert alert-danger d-flex align-items-center" role="alert">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
                <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                </svg>
                <div>
                    {% for key, error in form.errors.items %}
                        <strong>{{ error|escape }}</strong>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endif %}
        <div class="form-floating">
            {{ form.email }}
            <label for="floatingEmail" class="form-label">Email Address</label>
            <div class="invalid-tooltip">
                Please enter your email address
            </div>
        </div>
        <div class="buttons">
            <button id="resetBtn" class="btn btn-success btn.lg" type="submit">Reset</button>
            <a id="cancelBtn" href="{% url 'users:login' %}">Cancel</a>
        </div>
    </div>
</form>
{% endblock %}

users/templates/users/reset_password_sent.html
{% extends 'base_users.html' %}
{% block title %}Email Sent | StocksTracker{% endblock %}
{% block extra_head_content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'users/reset_password_sent.css' %}">
{% endblock %}
{% block content %}
<div class="resetText">
    <h2 class="reset">Password reset sent</h2>
</div>
<hr>
<div class="notification">
    <P>If you don't receive an email, please check your spam folder.</p>
    <p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>
    <a href="{% url 'users:reset_password' %}">Reset Again</a>
</div>
{% endblock %}