mainpage/urls.py
from django.urls import path

from mainpage import views as mainview

app_name = 'mainpage'
urlpatterns = [
    path('<int:pk>/home/', mainview.HomeView.as_view(), name='home'),
    path('<int:pk>/portfolio/', mainview.PortfolioView.as_view(), name='portfolio'),
    path('<int:pk>/update-portfolio/', mainview.UpdatePortfolioView.as_view(), name='update'),
    path('<int:pk>/transactions/', mainview.TransactionsListView.as_view(), name='transactions'),
    path('<int:pk>/edit-profile/', mainview.EditProfileView.as_view(), name='edit_profile'),
    path('<int:pk>/close-position/', mainview.ClosePositionView.as_view(), name='close_position'),
    path('<int:pk>/delete-transaction/', mainview.DeleteTransactionView.as_view(), name='delete_transaction'),
    # path('<int:pk>/edit-transaction/', mainview.EditTransactionView.as_view(), name='edit_transaction'),
]

stockstracker/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('user/', include('users.urls')),
    path('main/', include('mainpage.urls')),
    path('admin/', admin.site.urls),
]

users/urls.py
from audioop import reverse
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from users import views as user_view
from .forms import UserPasswordResetForm, UserSetPasswordForm

app_name = 'users'
urlpatterns = [
    path('register/', user_view.RegistrationView.as_view(), name='register'),
    path('login/', user_view.login_view, name='login'),
    path('logout/', user_view.logout_view, name='logout'),
    path(
        'reset-password/', 
        auth_views.PasswordResetView.as_view(
            form_class=UserPasswordResetForm,
            template_name="users/reset_password.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:reset_password_sent")), 
        name='reset_password'
        ),
    path(
        'reset-password-sent/', 
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/reset_password_sent.html",
            ), 
        name='reset_password_sent'),
    path(
        'reset/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(
            form_class=UserSetPasswordForm,
            template_name="users/password_reset_form.html",
            success_url=reverse_lazy("users:password_reset_complete")
            ), 
        name='password_reset_confirm'),
    path(
        'reset-password-complete/', 
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"), 
        name='password_reset_complete'),
]

mainpage/models.py
from django.db import models
from django.contrib.auth.models import User

class TickerSymbols(models.Model):
    tickersymbol = models.CharField(max_length=10)

    def __str__(self):
        return f"Ticker symbol: {self.tickersymbol}"

class Transaction(models.Model):
    buy = 'BUY'
    sell = 'SELL'
    transaction_type = [
        (buy, 'Buy'),
        (sell, 'Sell'),
    ]

    transaction = models.CharField(
        max_length=200,
        choices=transaction_type,
        default=buy,
    )

    symbol = models.CharField(max_length=10)
    transaction_date = models.DateField()
    share = models.DecimalField(decimal_places=4, max_digits=20)
    avg_price = models.DecimalField(decimal_places=8, max_digits=20)
    commission_fee = models.DecimalField(decimal_places=2, max_digits=3, default=0)
    cost_basis = models.DecimalField(decimal_places=8, max_digits=20)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class Portfolio(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    symbol = models.CharField(max_length=10)
    company_name = models.CharField(max_length=100)
    total_shares = models.DecimalField(decimal_places=4, max_digits=20)
    avg_price = models.DecimalField(decimal_places=8, max_digits=20)
    cost_basis = models.DecimalField(decimal_places=8, max_digits=20)
    current_value = models.DecimalField(decimal_places=8, max_digits=20)
    profit_loss = models.DecimalField(decimal_places=8, max_digits=20)

# To run under py manage.py shell:

# from mainpage.models import TickerSymbols
# from mainpage.API.tickersymbols import us_equities
# tickers = us_equities()
# objs = [TickerSymbols(tickersymbol=ticker) for ticker in tickers]
# TickerSymbols.objects.bulk_create(objs)

mainpage/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import FormView, ListView, TemplateView
from mainpage.models import Portfolio, Transaction, TickerSymbols
from .forms import UpdatePortfolioForm, EditProfileForm, ClosePositionForm
from .API.tickersymbols import *
from datetime import datetime
from decimal import Decimal

class HomeView(LoginRequiredMixin, TemplateView):

    template_name = 'mainpage/home.html'
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_user = self.request.user.id
        tickers = TickerSymbols.objects.all()
        portfolio = Portfolio.objects.filter(user_id=current_user).order_by('-current_value')
        buy_transactions = Transaction.objects.filter(user_id=current_user, transaction='BUY').order_by('-transaction_date')
        sell_transactions = Transaction.objects.filter(user_id=current_user, transaction='SELL').order_by('-transaction_date')
        indices = indices_performance()

        positions = portfolio.count()    
        if positions > 0:
            if positions >= 5:
                positions = 5
            top_tickers = []
            top_shares = []
            for position in portfolio[:positions]:
                top_tickers.append(position.symbol)
                top_shares.append(position.total_shares)
            latest_prices = get_latest_price(top_tickers)
            current_value = [shares * latest_price for shares, latest_price in zip(top_shares, latest_prices)]
            net_liquidity = sum(current_value)
            allocation_percentages = [(value/net_liquidity * 100) for value in current_value]
            top_holdings = zip(top_tickers, latest_prices, current_value)
            allocation = zip(top_tickers, allocation_percentages)
        else:
            top_holdings, net_liquidity, allocation = ([] for i in range(3))

        fields = [
                'tickers', 'buy_transactions', 'sell_transactions', 
                'top_holdings', 'net_liquidity', 'spy', 
                'nasdaq', 'djia', 'allocation'
                ]
        values = [
            tickers, buy_transactions, sell_transactions, 
            top_holdings, net_liquidity, indices['SPY'], 
            indices['QQQ'], indices['DIA'], allocation
            ]
        for field, value in zip(fields, values):
            context[field] = value
        return context


class PortfolioView(LoginRequiredMixin, TemplateView):
    
    template_name = 'mainpage/portfolio.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_user = self.request.user.id
        tickers = TickerSymbols.objects.all()
        portfolio = Portfolio.objects.filter(user_id=current_user).order_by('company_name')
        date = datetime.today().strftime('%d %b %Y %I:%M:%S %p')
        daily_percentage_changes, latest_prices = [], []
        daily_profit_loss = net_liquidity = net_profit_loss = 0
        positions = [position.symbol for position in portfolio]
        company_infos = company_quotes(positions)            
        for index, company in enumerate(company_infos):
            position = Portfolio.objects.filter(user_id=current_user, company_name__exact=company[0])
            previous_close = Decimal(company[2])
            latest_prices.append(Decimal(company[1]))
            total_shares = position.values('total_shares')[0].get('total_shares')
            current_value = latest_prices[index] * total_shares
            profit_loss = latest_prices[index] - previous_close
            daily_percentage_changes.append(profit_loss/previous_close * 100)
            daily_profit_loss += profit_loss * total_shares
            net_profit_loss += position.values('profit_loss')[0].get('profit_loss')
            net_liquidity += current_value
            position.update(current_value=current_value, profit_loss=current_value-position.values('cost_basis')[0].get('cost_basis'))

        context_fields = [
            'tickers', 
            'portfolio', 
            'portfolio_details', 
            'date', 
            'daily_profit_loss', 
            'net_liquidity', 
            'net_profit_loss'
            ]
        values = [
            tickers, 
            portfolio, 
            zip(daily_percentage_changes, latest_prices, portfolio), 
            date, 
            daily_profit_loss, 
            net_liquidity, 
            net_profit_loss
            ]

        for field, value in zip(context_fields, values):
            context[field] = value
        return context


class UpdatePortfolioView(LoginRequiredMixin, FormView):
    
    form_class = UpdatePortfolioForm
    template_name = 'mainpage/update_portfolio.html'

    def message(self, text):
        return messages.add_message(self.request, messages.INFO, text)

    def get_success_url(self):
        return reverse('mainpage:transactions', kwargs={'pk': self.request.user.id})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tickers'] = TickerSymbols.objects.all()
        return context

    def form_invalid(self, form):
        name_list = [
            'transaction', 'symbol', 'transaction_date', 
            'share', 'avg_price', 'cost_basis'
            ]
        # Print all applicable form fields
        [print(f"{name}: {form.cleaned_data.get(name)}") for name in name_list]
        # Print error(s) 
        print(form.errors)
        return super().form_invalid(form)

    def form_valid(self, form):
        transaction_form = form.save(commit=False)
        symbol = form.cleaned_data.get('symbol').upper()
        share = form.cleaned_data.get('share')
        average_price = form.cleaned_data.get('avg_price')
        total_cost = form.cleaned_data.get('cost_basis')
        transaction = form.cleaned_data.get('transaction')
        transaction_form.user_id = self.request.user.id
        transaction_form.symbol = symbol

        # API requests to extract appropriate data
        company_info = company_quotes(symbol)
        existing_position = Portfolio.objects.filter(user_id=self.request.user.id, symbol__exact=symbol)
        latest_price = Decimal(company_info[1])
        new_entry = {
            'avg_price': average_price,
            'company_name': company_info[0],
            'cost_basis': total_cost,
            'current_value': share * latest_price,
            'profit_loss': share * latest_price - total_cost,
            'symbol': symbol,
            'total_shares': share,
        }

        # Check if there is any existing position before selling
        if transaction == 'SELL' and not existing_position.exists():
            self.message(f'Fail to sell, you currently do not have any position in {symbol}')
            return super().form_invalid(form)

        position, created = Portfolio.objects.get_or_create(
                                            symbol__exact=symbol, 
                                            user_id=self.request.user.id,
                                            defaults=new_entry
                                            )

        if created:
            message = f"Successfully opened a new position in {symbol}"
        
        while not created:
            current_shares = position.total_shares
            current_cost_basis = position.cost_basis
            # Check whether selling position is bigger than existing position
            if transaction == 'SELL':
                updated_shares = current_shares - share
                if updated_shares < 0:
                    self.message(f'Fail to sell, do not exceed {current_shares} {symbol} shares')
                    return super().form_invalid(form)
                elif updated_shares > 0:
                    updated_cost_basis = current_cost_basis - total_cost
                    message = f"Sale of {share} {symbol} share(s) has been updated to your portfolio"
                else:
                    position.delete()
                    break
            else:
                updated_shares = current_shares + share
                updated_cost_basis = current_cost_basis + total_cost
                message = f"Purchase of {share} {symbol} share(s) has been updated to your portfolio"

            updated_avg_price = updated_cost_basis / updated_shares
            updated_current_value = updated_shares * latest_price
            updated_pl = updated_current_value - updated_cost_basis
            # Update Portfolio database
            position.total_shares=updated_shares,
            position.cost_basis=updated_cost_basis,
            position.avg_price=updated_avg_price,
            position.current_value=updated_current_value,
            position.profit_loss=updated_pl
            position.save()
            break
            
        transaction_form.save()
        self.message(message)
        if 'confirm' in self.request.POST:
            # Redirect to URL under get_success_url
            return super().form_valid(form)
        # if 'Submit and add another' button is clicked
        return redirect(reverse('mainpage:update', kwargs={'pk': self.request.user.id}))


class TransactionsListView(LoginRequiredMixin, ListView):
    
    model = Transaction
    template_name = 'mainpage/transactions.html'
        
    def get_queryset(self):
        queryset = super().get_queryset()
        # Get data from the correct user
        transaction_queryset = queryset.filter(user_id=self.request.user.id).order_by('-transaction_date')
        return transaction_queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

mainpage/templates/base_mainpage.html
<!DOCTYPE html>
<html lang='en'>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width initial-scale=1.0">
        <!--Load bootstrap library-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto&family=Sora&display=swap" rel="stylesheet">
        {% load static %}
        <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
        <link rel="stylesheet" type="text/css" href="{% static 'mainpage/base_mainpage.css' %}">
        <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
        <!--Place title of the webpage here-->
        <title>{% block title %}{% endblock %}</title>
        {% block extra_head_content %}{% endblock %}
    </head>
    <body>
        <div class="page-container">
            <div class="content-wrap">
                <div class="sidebar">
                    <div id="webname">
                        <p><strong>StocksTracker</strong></p>
                        <hr>
                    </div>
                    <div class="link">
                        <a href="{% url 'mainpage:home' user.id %}"><i class="fa-solid fa-bars"></i>Summary</a>
                    </div>
                    <div class="link">
                        <a href="{% url 'mainpage:portfolio' user.id %}"><i class="fa-solid fa-chart-line"></i>Portfolio</a>
                    </div>
                    <div class="link">
                        <a href="{% url 'mainpage:update' user.id %}"><i class="fa-solid fa-file-pen"></i>Update Portfolio</a>
                    </div>
                    <div class="link">
                        <a href="{% url 'mainpage:transactions' user.id %}"><i class="fa-solid fa-table-list"></i></i>Transactions</a>
                    </div>
                </div>
                <nav class="navbar">
                    <div>
                        <form action="https://finance.yahoo.com/q" method="GET" target="_blank" rel="noopener noreferrer">
                            <input class="search" type="text" list="tickers" placeholder="Search Ticker" name="s">
                                <datalist id="tickers">
                                {% for ticker in tickers %}
                                    <option value="{{ ticker.tickersymbol }}"></option>
                                {% endfor %}
                            </datalist>
                            <button id="search" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
                        </form>
                    </div>
                    <div class="dropdown">
                        <div class="profile">
                            {% if request.user.is_authenticated %}
                                <button>
                                    Welcome, {{ user.get_username }}
                                    <i class="fa-regular fa-user"></i>
                                </button>
                            {% else %}
                                <button>
                                    Login
                                    <i class="fa-regular fa-user"></i>
                                </button>
                            {% endif %}
                            <ul>
                                <li>
                                    <a href="{% url 'mainpage:edit_profile' user.id %}">
                                    <i class="fa-solid fa-user-pen"></i>
                                    Edit Profile
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'users:logout' %}">
                                    <i class="fa-solid fa-power-off"></i>
                                    Log Out
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <p class="solid"></p>
                </nav>
                {% block content %}{% endblock %}
            </div>
            <footer>
                <div class="container-footer">
                    <ul class="links">
                        <li>
                            <a href="https://finance.yahoo.com/" target="_blank" rel="noopener noreferrer"><i class="fa-brands fa-yahoo"></i>&nbsp;Yahoo! Finance</a>
                        </li>
                        <li>
                            <a href="https://www.google.com/finance/?hl=en" target="_blank" rel="noopener noreferrer"><i class="fa-brands fa-google"></i>&nbsp;Google Finance</a>
                        </li>
                        <li>
                            <a href="https://finviz.com/" target="_blank" rel="noopener noreferrer"><i class="fa-solid fa-comments-dollar"></i>&nbsp;FINVIZ</a>
                        </li>
                        <li>
                            <a href="https://finviz.com/map.ashx?t=sec" target="_blank" rel="noopener noreferrer"><i class="fa-solid fa-map"></i>&nbsp;S&P500 Map</a>
                        </li>
                        <li>
                            <a href="https://www.marketwatch.com/" target="_blank" rel="noopener noreferrer"><i class="fa-solid fa-arrow-trend-up"></i>&nbsp;MarketWatch</a>
                        </li>
                    </ul>
                    <hr>
                    <p class="dataprovidedby">Data powered by<a href="https://iexcloud.io/">IEX Cloud</a></p>
                </div>
            </footer>
        </div>
    </body>
</html>