mainpage/urls.py
from django.urls import path

from mainpage import views as mainview

app_name = 'mainpage'
urlpatterns = [
    path('<int:pk>/home/', mainview.HomeView.as_view(), name='home'),
    path('<int:pk>/portfolio/', mainview.PortfolioView.as_view(), name='portfolio'),
    path('<int:pk>/update-portfolio/', mainview.UpdatePortfolioView.as_view(), name='update'),
    path('<int:pk>/transactions/', mainview.TransactionsListView.as_view(), name='transactions'),
    path('<int:pk>/edit-profile/', mainview.EditProfileView.as_view(), name='edit_profile'),
    path('<int:pk>/close-position/', mainview.ClosePositionView.as_view(), name='close_position'),
    path('<int:pk>/delete-transaction/', mainview.DeleteTransactionView.as_view(), name='delete_transaction'),
    # path('<int:pk>/edit-transaction/', mainview.EditTransactionView.as_view(), name='edit_transaction'),
]

stockstracker/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('user/', include('users.urls')),
    path('main/', include('mainpage.urls')),
    path('admin/', admin.site.urls),
]

users/urls.py
from audioop import reverse
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from users import views as user_view
from .forms import UserPasswordResetForm, UserSetPasswordForm

app_name = 'users'
urlpatterns = [
    path('register/', user_view.RegistrationView.as_view(), name='register'),
    path('login/', user_view.login_view, name='login'),
    path('logout/', user_view.logout_view, name='logout'),
    path(
        'reset-password/', 
        auth_views.PasswordResetView.as_view(
            form_class=UserPasswordResetForm,
            template_name="users/reset_password.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:reset_password_sent")), 
        name='reset_password'
        ),
    path(
        'reset-password-sent/', 
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/reset_password_sent.html",
            ), 
        name='reset_password_sent'),
    path(
        'reset/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(
            form_class=UserSetPasswordForm,
            template_name="users/password_reset_form.html",
            success_url=reverse_lazy("users:password_reset_complete")
            ), 
        name='password_reset_confirm'),
    path(
        'reset-password-complete/', 
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"), 
        name='password_reset_complete'),
]

mainpage/models.py
from django.db import models
from django.contrib.auth.models import User

class TickerSymbols(models.Model):
    tickersymbol = models.CharField(max_length=10)

    def __str__(self):
        return f"Ticker symbol: {self.tickersymbol}"

class Transaction(models.Model):
    buy = 'BUY'
    sell = 'SELL'
    transaction_type = [
        (buy, 'Buy'),
        (sell, 'Sell'),
    ]

    transaction = models.CharField(
        max_length=200,
        choices=transaction_type,
        default=buy,
    )

    symbol = models.CharField(max_length=10)
    transaction_date = models.DateField()
    share = models.DecimalField(decimal_places=4, max_digits=20)
    avg_price = models.DecimalField(decimal_places=8, max_digits=20)
    commission_fee = models.DecimalField(decimal_places=2, max_digits=3, default=0)
    cost_basis = models.DecimalField(decimal_places=8, max_digits=20)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class Portfolio(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    symbol = models.CharField(max_length=10)
    company_name = models.CharField(max_length=100)
    total_shares = models.DecimalField(decimal_places=4, max_digits=20)
    avg_price = models.DecimalField(decimal_places=8, max_digits=20)
    cost_basis = models.DecimalField(decimal_places=8, max_digits=20)
    current_value = models.DecimalField(decimal_places=8, max_digits=20)
    profit_loss = models.DecimalField(decimal_places=8, max_digits=20)

# To run under py manage.py shell:

# from mainpage.models import TickerSymbols
# from mainpage.API.tickersymbols import us_equities
# tickers = us_equities()
# objs = [TickerSymbols(tickersymbol=ticker) for ticker in tickers]
# TickerSymbols.objects.bulk_create(objs)

mainpage/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import FormView, ListView, TemplateView
from mainpage.models import Portfolio, Transaction, TickerSymbols
from .forms import UpdatePortfolioForm, EditProfileForm, ClosePositionForm
from .API.tickersymbols import *
from datetime import datetime
from decimal import Decimal

class HomeView(LoginRequiredMixin, TemplateView):

    template_name = 'mainpage/home.html'
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_user = self.request.user.id
        tickers = TickerSymbols.objects.all()
        portfolio = Portfolio.objects.filter(user_id=current_user).order_by('-current_value')
        buy_transactions = Transaction.objects.filter(user_id=current_user, transaction='BUY').order_by('-transaction_date')
        sell_transactions = Transaction.objects.filter(user_id=current_user, transaction='SELL').order_by('-transaction_date')
        indices = indices_performance()

        positions = portfolio.count()    
        if positions > 0:
            if positions >= 5:
                positions = 5
            top_tickers = []
            top_shares = []
            for position in portfolio[:positions]:
                top_tickers.append(position.symbol)
                top_shares.append(position.total_shares)
            latest_prices = get_latest_price(top_tickers)
            current_value = [shares * latest_price for shares, latest_price in zip(top_shares, latest_prices)]
            net_liquidity = sum(current_value)
            allocation_percentages = [(value/net_liquidity * 100) for value in current_value]
            top_holdings = zip(top_tickers, latest_prices, current_value)
            allocation = zip(top_tickers, allocation_percentages)
        else:
            top_holdings, net_liquidity, allocation = ([] for i in range(3))

        fields = [
                'tickers', 'buy_transactions', 'sell_transactions', 
                'top_holdings', 'net_liquidity', 'spy', 
                'nasdaq', 'djia', 'allocation'
                ]
        values = [
            tickers, buy_transactions, sell_transactions, 
            top_holdings, net_liquidity, indices['SPY'], 
            indices['QQQ'], indices['DIA'], allocation
            ]
        for field, value in zip(fields, values):
            context[field] = value
        return context


class PortfolioView(LoginRequiredMixin, TemplateView):
    
    template_name = 'mainpage/portfolio.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_user = self.request.user.id
        tickers = TickerSymbols.objects.all()
        portfolio = Portfolio.objects.filter(user_id=current_user).order_by('company_name')
        date = datetime.today().strftime('%d %b %Y %I:%M:%S %p')
        daily_percentage_changes, latest_prices = [], []
        daily_profit_loss = net_liquidity = net_profit_loss = 0
        positions = [position.symbol for position in portfolio]
        company_infos = company_quotes(positions)            
        for index, company in enumerate(company_infos):
            position = Portfolio.objects.filter(user_id=current_user, company_name__exact=company[0])
            previous_close = Decimal(company[2])
            latest_prices.append(Decimal(company[1]))
            total_shares = position.values('total_shares')[0].get('total_shares')
            current_value = latest_prices[index] * total_shares
            profit_loss = latest_prices[index] - previous_close
            daily_percentage_changes.append(profit_loss/previous_close * 100)
            daily_profit_loss += profit_loss * total_shares
            net_profit_loss += position.values('profit_loss')[0].get('profit_loss')
            net_liquidity += current_value
            position.update(current_value=current_value, profit_loss=current_value-position.values('cost_basis')[0].get('cost_basis'))

        context_fields = [
            'tickers', 
            'portfolio', 
            'portfolio_details', 
            'date', 
            'daily_profit_loss', 
            'net_liquidity', 
            'net_profit_loss'
            ]
        values = [
            tickers, 
            portfolio, 
            zip(daily_percentage_changes, latest_prices, portfolio), 
            date, 
            daily_profit_loss, 
            net_liquidity, 
            net_profit_loss
            ]

        for field, value in zip(context_fields, values):
            context[field] = value
        return context


class UpdatePortfolioView(LoginRequiredMixin, FormView):
    
    form_class = UpdatePortfolioForm
    template_name = 'mainpage/update_portfolio.html'

    def message(self, text):
        return messages.add_message(self.request, messages.INFO, text)

    def get_success_url(self):
        return reverse('mainpage:transactions', kwargs={'pk': self.request.user.id})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tickers'] = TickerSymbols.objects.all()
        return context

    def form_invalid(self, form):
        name_list = [
            'transaction', 'symbol', 'transaction_date', 
            'share', 'avg_price', 'cost_basis'
            ]
        # Print all applicable form fields
        [print(f"{name}: {form.cleaned_data.get(name)}") for name in name_list]
        # Print error(s) 
        print(form.errors)
        return super().form_invalid(form)

    def form_valid(self, form):
        transaction_form = form.save(commit=False)
        symbol = form.cleaned_data.get('symbol').upper()
        share = form.cleaned_data.get('share')
        average_price = form.cleaned_data.get('avg_price')
        total_cost = form.cleaned_data.get('cost_basis')
        transaction = form.cleaned_data.get('transaction')
        transaction_form.user_id = self.request.user.id
        transaction_form.symbol = symbol

        # API requests to extract appropriate data
        company_info = company_quotes(symbol)
        existing_position = Portfolio.objects.filter(user_id=self.request.user.id, symbol__exact=symbol)
        latest_price = Decimal(company_info[1])
        new_entry = {
            'avg_price': average_price,
            'company_name': company_info[0],
            'cost_basis': total_cost,
            'current_value': share * latest_price,
            'profit_loss': share * latest_price - total_cost,
            'symbol': symbol,
            'total_shares': share,
        }

        # Check if there is any existing position before selling
        if transaction == 'SELL' and not existing_position.exists():
            self.message(f'Fail to sell, you currently do not have any position in {symbol}')
            return super().form_invalid(form)

        position, created = Portfolio.objects.get_or_create(
                                            symbol__exact=symbol, 
                                            user_id=self.request.user.id,
                                            defaults=new_entry
                                            )

        if created:
            message = f"Successfully opened a new position in {symbol}"
        
        while not created:
            current_shares = position.total_shares
            current_cost_basis = position.cost_basis
            # Check whether selling position is bigger than existing position
            if transaction == 'SELL':
                updated_shares = current_shares - share
                if updated_shares < 0:
                    self.message(f'Fail to sell, do not exceed {current_shares} {symbol} shares')
                    return super().form_invalid(form)
                elif updated_shares > 0:
                    updated_cost_basis = current_cost_basis - total_cost
                    message = f"Sale of {share} {symbol} share(s) has been updated to your portfolio"
                else:
                    position.delete()
                    break
            else:
                updated_shares = current_shares + share
                updated_cost_basis = current_cost_basis + total_cost
                message = f"Purchase of {share} {symbol} share(s) has been updated to your portfolio"

            updated_avg_price = updated_cost_basis / updated_shares
            updated_current_value = updated_shares * latest_price
            updated_pl = updated_current_value - updated_cost_basis
            # Update Portfolio database
            position.total_shares=updated_shares,
            position.cost_basis=updated_cost_basis,
            position.avg_price=updated_avg_price,
            position.current_value=updated_current_value,
            position.profit_loss=updated_pl
            position.save()
            break
            
        transaction_form.save()
        self.message(message)
        if 'confirm' in self.request.POST:
            # Redirect to URL under get_success_url
            return super().form_valid(form)
        # if 'Submit and add another' button is clicked
        return redirect(reverse('mainpage:update', kwargs={'pk': self.request.user.id}))


class TransactionsListView(LoginRequiredMixin, ListView):
    
    model = Transaction
    template_name = 'mainpage/transactions.html'
        
    def get_queryset(self):
        queryset = super().get_queryset()
        # Get data from the correct user
        transaction_queryset = queryset.filter(user_id=self.request.user.id).order_by('-transaction_date')
        return transaction_queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

mainpage/templates/mainpage/close_position.html
{% extends 'base_mainpage.html' %}
{% block title %}Close Position | StocksTracker {% endblock %}
{% block extra_head_content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'mainpage/update_portfolio.css' %}">
<script defer src="{% static 'mainpage/calculation.js' %}"></script>
{% endblock %}
{% block content %}
<div class="container">
    <div class="content">
        <h2><i class="fa-solid fa-file-pen"></i>Close Position</h2>
        {{ form.non_field_errors }}
        {% if form.errors %}
        <div class="alert alert-danger alert-dismissible fade show d-flex align-items-center" role="alert">
            {% if form.transaction_date.errors %}
                {% for error in form.avg_price.errors %}
                    <strong>{{ error|escape }}</strong>
                {% endfor %}
            {% endif %}
            {% if form.avg_price.errors %}
                {% for error in form.avg_price.errors %}
                    <strong>{{ error|escape }}</strong>
                {% endfor %}
            {% endif %}
            {% if form.commission_fee.errors %}
                {% for error in form.commission_fee.errors %}
                    <strong>{{ error|escape }}</strong>
                {% endfor %}
            {% endif %}
        </div>
        {% endif %}
        <form method="POST" action="{% url 'mainpage:close_position' position.id %}">
            {% csrf_token %}
            <div class="row1">
                <div class="transaction_type col-6">
                    <p>Transaction Type</p>
                    <select name="transaction" id="transaction_type" class="form-select">
                        {% for value, text in form.transaction.field.choices %}
                        <option value="{{ value }}" id="sell">{{ text }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="symbol col-6">
                    <label for="floatingSymbol" class="form-label">Ticker</label>
                    {{ form.symbol }}
                    <datalist id="tickers">
                        {% for ticker in tickers %}
                            <option value="{{ ticker.tickersymbol }}"></option>
                        {% endfor %}
                    </datalist>
                </div>
            </div>
            <div class="row2">
                <div class="transaction_date col-12">
                    <p>Closed On</p>
                    {{ form.transaction_date }}
                </div>
            </div>
            <div class="row3">
                <div class="shares col-3">
                    <p>Shares</p>
                    {{ form.share }}
                </div>
                <div class="avgP col-3">
                    <p>Average Price&nbsp;<i class="fa-solid fa-dollar-sign"></i></p>
                    {{ form.avg_price }}
                </div>
                <div class="commission col-3">
                    <p>Commission Fee&nbsp;<i class="fa-solid fa-dollar-sign"></i></p>
                    {{ form.commission_fee }}
                </div>
                <div class="costB col-3">
                    <p>Cost Basis&nbsp;<i class="fa-solid fa-dollar-sign"></i></p>
                    {{ form.cost_basis }}
                </div>
            </div>
            <div class="buttons">
                <button id="submit" name="confirm" type="submit" value="Submit">Submit</button>
                <a href="{% url 'mainpage:portfolio' user.id %}" class="btn btn-danger" id="cancel">Cancel</a>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

mainpage/templates/mainpage/delete_transaction.html
{% extends 'base_mainpage.html' %}
{% block title %}Delete | StocksTracker{% endblock %}
{% block extra_head_content %}
{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'mainpage/delete_transaction.css' %}">
{% endblock %}
{% block content %}
<div class="deleteContainer">
    <div class="deleteContent">
    <h3><i class="fa-solid fa-trash-can"></i>&nbsp;Delete the following?</h3>
    <table class="table table-dark table-striped table-hover" cell-spacing="0">
        <thead>
            <tr>
                <th scope="col">Type</th>
                <th scope="col">Date</th>
                <th scope="col">Symbol</th>
                <th scope="col">Shares</th>
                <th scope="col">Average Price ($)</th>
                <th scope="col">Cost Basis ($)</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ transaction.transaction }}</td>
                <td>{{ transaction.transaction_date }}</td>
                <td>{{ transaction.symbol }}</td>
                <td>{{ transaction.share|floatformat:-4 }}</td>
                <td>{{ transaction.avg_price|floatformat:-2 }}</td>
                <td>{{ transaction.cost_basis|floatformat:-2 }}</td>
            </tr>
        </tbody>
    </table>
    <form method="post" action="">
        {% csrf_token %}
        <button class="btn btn-success" type="submit">Yes</button>
        <button class="btn btn-danger" id="cancel" type="button">
            <a id="cancel" href="{% url 'mainpage:transactions' user.id %}">Cancel</a>
        </button>
    </form>
    </div>
</div>
{% endblock %}

mainpage/templates/mainpage/edit_profile.html
{% extends 'base_mainpage.html' %}
{% block title %}Edit Profile | StocksTracker{% endblock %}
{% block extra_head_content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'mainpage/edit_profile.css' %}">
{% endblock %}
{% block content %}
<div class="container">
    <div class="content">
        <h2 class="profile"><i class="fa-solid fa-user-pen"></i>&nbsp;Edit Profile</h2>
        <div id=formerrors class="errors col-12">
            {{ form.non_field_errors }}
            {% if form.errors %}
                <div id=errors class="alert alert-danger alert-dismissible fade show d-flex align-items-center" role="alert">
                    <div>
                        <ul>
                        {% if form.password.errors %}
                            {% for error in form.password.errors %}
                            <li><strong>{{ error|escape }}</strong></li>
                            {% endfor %}
                        {% endif %}
                        {% if form.password2.errors %}
                            {% for error in form.password2.errors %}
                            <li><strong>{{ error|escape }}</strong></li>
                            {% endfor %}
                        {% endif %}
                        </ul>
                    </div>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endif %}
        </div>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        <form id=edit-profile action="{% url 'mainpage:edit_profile' user.id %}" method="POST">
            {% csrf_token %}
            <div class="user-info">
                <h3><i class="fa-solid fa-user"></i>&nbsp;User Info</h3>
                <div class="user">
                    <div class="username col-6">
                        <label for="username" class="form-label">Username</label>
                        {{ form.username }}
                    </div>
                    <div class="email col-6">
                        <label for="email" class="form-label">Email Address</label>
                        <input readonly class="form-control" type="text" id="email" name="email" value="{{ email }}">
                    </div>
                </div>
                <div class="name">
                    <div class="firstname col-6">
                        <label for="firstname">First Name</label>
                        <input class="form-control" type="text" id="firstname" name="firstname" value="{{ first_name }}">
                    </div>
                    <div class="lastname col-6">
                        <label for="lastname">Last Name</label>
                        <input class="form-control" type="text" id="lastname" name="lastname" value="{{ last_name }}">
                    </div>
                </div>
            </div>
            <hr id="breakpage">
            <div class="passwords">
                <h3><i class="fa-solid fa-user-lock"></i>&nbsp;Change Password</h3>
                <div class="password col-12">
                    <label for="password" class="form-label">Old Password</label>
                    {{ form.password }}
                    <div class="invalid-feedback">
                        Please enter the old password
                    </div>
                </div>
                <div class="new_password">
                    <div class="password1 col-6">
                        <label for="password1" class="form-label">New Password</label>
                        {{ form.password1 }}
                        <div class="invalid-feedback">
                            Please enter the new password
                        </div>
                    </div>
                    <div class="password2 col-6">
                        <label for="password2" class="form-label">Confirm Password</label>
                        {{ form.password2 }}
                        <div class="invalid-feedback">
                            Please enter the new password again
                        </div>
                    </div>
                </div>
            </div>
            <div class="buttons">
                <button id="submit" type="submit" value="Save">Save Changes</button>
                <a href="{% url 'mainpage:portfolio' user.id %}" class="btn btn-danger" id="cancel">Cancel</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

mainpage/templates/mainpage/portfolio.html
{% extends 'base_mainpage.html' %}
{% block title %}Portfolio | StocksTracker{% endblock %}
{% block extra_head_content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'mainpage/portfolio.css' %}">
{% endblock %}
{% block content %}
<div class="container">
    {% if messages %}
    <div class="message">
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
    <div class="portfolio">
        <div class="title">
            <h2><i class="fa-solid fa-chart-line"></i>&nbsp;Portfolio</h2>
            {% if portfolio %}
            <div class="info">
                <div class="date"><span><p>As of {{ date }}</p><button onClick="window.location.reload();"><i class="fa-solid fa-arrows-rotate"></i></button></span></div>
                <div class="net_liquidity">
                    <p>Net Liquidity</p>
                    <span><i class="fa-solid fa-dollar-sign"></i>{{ net_liquidity|floatformat:-2 }}</span>
                </div>
                <div class="net_profit_loss">
                    <p>Net P/L</p>
                    {% if net_profit_loss == 0 %}
                    <span>
                    {% elif net_profit_loss > 0 %}
                    <span id="positive">
                    {% else %}
                    <span id="negative">
                    {% endif %}
                        <i class="fa-solid fa-dollar-sign"></i>{{ net_profit_loss|floatformat:-2 }}
                    </span>
                </div>
                <div class="daily_pl">
                    <p>Daily P/L</p>
                    {% if daily_profit_loss == 0 %}
                    <span>
                    {% elif daily_profit_loss > 0 %}
                    <span id="positive">
                    {% else %}
                    <span id="negative">
                    {% endif %}
                        <i class="fa-solid fa-dollar-sign"></i>{{ daily_profit_loss|floatformat:-2 }}
                    </span>
                </div>
            </div>
        </div> 
        <div class="table-wrap">
            <table class="table table-dark table-striped table-hover">
                <thead>
                    <tr>
                        <th scope="col"><i class="fa-solid fa-table-list"></i>&nbsp;&nbsp;Ticker</th>
                        <th scope="col"><i class="fa-solid fa-arrow-up-1-9"></i>&nbsp;&nbsp;Shares</th>
                        <th scope="col"><i class="fa-solid fa-percent"></i>&nbsp;&nbsp;Daily</th>
                        <th scope="col"><i class="fa-solid fa-dollar-sign"></i>&nbsp;&nbsp;Last Price</th>
                        <th scope="col"><i class="fa-solid fa-dollar-sign"></i>&nbsp;&nbsp;Avg Price</th>
                        <th scope="col"><i class="fa-solid fa-dollar-sign"></i>&nbsp;&nbsp;Cost Basis</th>
                        <th scope="col"><i class="fa-solid fa-dollar-sign"></i>&nbsp;&nbsp;Current Value</th>
                        <th scope="col"><i class="fa-solid fa-dollar-sign"></i>&nbsp;&nbsp;P/L</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for daily_pc, price, position in portfolio_details %}
                    <tr>
                        <th scope="row">
                            <a href="https://finance.yahoo.com/quote/{{ position.symbol }}" target="_blank" rel="noopener noreferrer">
                                {{ position.symbol }}
                            </a>
                        </th>
                        <td>{{ position.total_shares }}</td>
                        {% if daily_pc == 0 %}
                        <td>
                        {% elif daily_pc >= 0 %}
                        <td id="positive">
                        {% else %}
                        <td id="negative">
                        {% endif %}
                            {{ daily_pc|floatformat:-2 }}
                        </td>
                        <td>{{ price|floatformat:-2 }}</td>
                        <td>{{ position.avg_price|floatformat:-2 }}</td>
                        <td>{{ position.cost_basis|floatformat:-2 }}</td>
                        <td>{{ position.current_value|floatformat:-2 }}</td>
                        {% if position.profit_loss == 0 %}
                        <td>
                        {% elif position.profit_loss > 0 %}
                        <td id="positive">
                        {% else %}
                        <td id="negative">
                        {% endif %}
                            {{ position.profit_loss|floatformat:-2 }}
                        </td>
                        <td>
                            <div class="btn-group dropstart">
                                <button type="button" class="action" value="{{ portfolio.id }}" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="fa-solid fa-ellipsis-vertical"></i>
                                </button>
                                <ul class="dropdown-menu">
                                    <li id="buysell"><a href="{% url 'mainpage:update' user.id %}">Buy / Sell</a></li>
                                    <li id="close"><a href="{% url 'mainpage:close_position' position.id %}">Close Position</a></li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
        <p class="no_position">You do not have any position, click 
            <span class=update><a href="{% url 'mainpage:update' user.id %}">here</a></span>
            to add
        </p>
        {% endif %}
    </div>
</div>
{% endblock %}